FROM jupyter/scipy-notebook

RUN pip install plotly & \
    export NODE_OPTIONS=--max-old-space-size=4096 && \
    jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.0 --no-build && \
    jupyter labextension install jupyterlab-plotly@1.1.0 --no-build && \
    jupyter labextension install plotlywidget@1.1.0 --no-build && \
    jupyter labextension install jupyterlab-chart-editor@1.2 --no-build && \
    jupyter lab build && \
    unset NODE_OPTIONS

EXPOSE 8888

CMD ["jupyter", "lab"]
